/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oopatm;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tadija
 */
public class ATMLoginForm extends JFrame implements ActionListener {

    /**
     * Creates new form ATMLoginForm
     */
    public ATMLoginForm() {
        initComponents();
        initEventListeners();
        jPanel_loginScreen.setVisible(true);
        jPanel_adminControlPanel.setVisible(false);
    }
    
    private void initEventListeners() {
        jbtn_login.addActionListener(this);
        jbtn_savingsAcc.addActionListener(this);
        jbtn_currentAcc.addActionListener(this);
        jbtn_changePin.addActionListener(this);
        jbtn_back.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPane = new javax.swing.JLayeredPane();
        jPanel_loginScreen = new javax.swing.JPanel();
        jbtn_login = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jlbl_title = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jtxt_username = new javax.swing.JTextField();
        jPanel_adminControlPanel = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jbtn_currentAcc = new javax.swing.JButton();
        jbtn_savingsAcc = new javax.swing.JButton();
        jbtn_changePin = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_login.setText("Login");

        jpassword.setText("password");

        jlbl_title.setText("Login screen");

        jLabel_username.setText("username");

        jLabel_password.setText("password");

        jtxt_username.setText("type your username");

        javax.swing.GroupLayout jPanel_loginScreenLayout = new javax.swing.GroupLayout(jPanel_loginScreen);
        jPanel_loginScreen.setLayout(jPanel_loginScreenLayout);
        jPanel_loginScreenLayout.setHorizontalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl_title)
                            .addComponent(jbtn_login)))
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_username)
                            .addComponent(jLabel_password))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel_loginScreenLayout.setVerticalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jlbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_username)
                    .addComponent(jtxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password))
                .addGap(67, 67, 67)
                .addComponent(jbtn_login)
                .addGap(67, 67, 67))
        );

        jlblTitle.setText("Admin control panel");

        jbtn_currentAcc.setText("Create new current account");

        jbtn_savingsAcc.setText("Create new savings account");

        jbtn_changePin.setText("Change pin on existing account");

        jbtn_back.setText("Go Back");

        javax.swing.GroupLayout jPanel_adminControlPanelLayout = new javax.swing.GroupLayout(jPanel_adminControlPanel);
        jPanel_adminControlPanel.setLayout(jPanel_adminControlPanelLayout);
        jPanel_adminControlPanelLayout.setHorizontalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_savingsAcc)
                            .addComponent(jbtn_currentAcc)
                            .addComponent(jbtn_changePin)
                            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jbtn_back))))
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jlblTitle)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel_adminControlPanelLayout.setVerticalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jlblTitle)
                .addGap(34, 34, 34)
                .addComponent(jbtn_currentAcc)
                .addGap(18, 18, 18)
                .addComponent(jbtn_savingsAcc)
                .addGap(18, 18, 18)
                .addComponent(jbtn_changePin)
                .addGap(41, 41, 41)
                .addComponent(jbtn_back)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLPane.setLayer(jPanel_loginScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_adminControlPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPaneLayout = new javax.swing.GroupLayout(jLPane);
        jLPane.setLayout(jLPaneLayout);
        jLPaneLayout.setHorizontalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPaneLayout.setVerticalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean userNamePasswordIsCorrect (String inputUsername, char[] inputPassword) {
        boolean userNamePasswordIsCorrect =true;
        return userNamePasswordIsCorrect;
    }
    @Override
    public void actionPerformed (ActionEvent e){
        String url = "accountData.data";
        File file = new File(url);
        System.out.println("action received...");
        
        if (e.getSource()==jbtn_login) { 
            
                if (adminUsernameIsCorrect(jtxt_username.getText())&&adminPasswordIsCorrect(jpassword.getPassword())) {
                    System.out.println("admin account recognized... starting admin control panel");
                    jPanel_loginScreen.setVisible(false);
                    jPanel_adminControlPanel.setVisible(true);
                }
                else if (!file.exists()) {
                    System.out.println("No accounts in the bank!");
                }
                else if(userNamePasswordIsCorrect(jtxt_username.getText(),jpassword.getPassword())) {///UNFINISHED!!!!! 
                    System.out.println("Record was found in the file.");
                    System.out.println("Print account details.");
                
                }
        }
        if (e.getSource()==jbtn_currentAcc)  {
                System.out.println("current account button pressed...");
                
                ArrayList<Accounts> accounts = new ArrayList<Accounts>();
                if (file.exists()) {
                    try {

                        FileInputStream fi = new FileInputStream(file);
                        ObjectInputStream oi = new ObjectInputStream(fi);

                        accounts  = (ArrayList<Accounts>) oi.readObject();
                           
                        oi.close();
                        fi.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing stream");
                    } catch (ClassNotFoundException e2) {
                        System.out.println("Class not found");
                    }

                
                }
                else {
                    System.out.println("file doesnt exist yet!");
                    try {
                        file.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(ATMLoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    System.out.println("file created!");
                }
                
        }
        else if (e.getSource()==jbtn_savingsAcc) {
            System.out.println("savings account button pressed...");
        }
        else if (e.getSource()==jbtn_changePin) {
            System.out.println("change pin button pressed...");
        }
        else if (e.getSource()==jbtn_back) {
            System.out.println("go back button pressed...");
            jPanel_adminControlPanel.setVisible(false);
            jPanel_loginScreen.setVisible(true);
            
        }
        else System.err.println("Unhandled event....");
        
    }
    
    private boolean adminUsernameIsCorrect (String inputUsername) {
        boolean isCorrect = true;
        String adminUsername = "admin";
        if (!inputUsername.matches(adminUsername)) isCorrect = false;
        return isCorrect;
    }
    private boolean adminPasswordIsCorrect (char[] inputPassword) {
        
        //function referenced from oracle docs: https://docs.oracle.com/javase/tutorial/uiswing/components/passwordfield.html
        boolean isCorrect = true;
        char[] adminPassword = { 'a', 'd', 'm', 'i', 'n'};
        if (inputPassword.length != adminPassword.length) {
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals (inputPassword, adminPassword);
        }
        //Zero out the password, for security
        Arrays.fill(adminPassword,'0');
        return isCorrect;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLPane;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel_adminControlPanel;
    private javax.swing.JPanel jPanel_loginScreen;
    private javax.swing.JButton jbtn_back;
    private javax.swing.JButton jbtn_changePin;
    private javax.swing.JButton jbtn_currentAcc;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JButton jbtn_savingsAcc;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlbl_title;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtxt_username;
    // End of variables declaration//GEN-END:variables
}
