/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oopatm;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.Arrays;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tadija
 */
public class ATMLoginForm extends JFrame implements ActionListener {

    /**
     * Creates new form ATMLoginForm
     */
    private ArrayList<Accounts> accounts = new ArrayList<Accounts>();
    public ATMLoginForm() {
        initComponents();
        initEventListeners();
        jPanel_loginScreen.setVisible(true);
        jPanel_adminControlPanel.setVisible(false);
        jPanel_createNewCurrentAcc.setVisible(false);
        jPanel_userInterfaceCurrentAcc.setVisible(false);
        jPanel_createSavingsAcc.setVisible(false);
        jPanel_userInterfaceSavingAcc.setVisible(false);
        clearTextFields();
    }
    
    private void initEventListeners() {
        jbtn_login.addActionListener(this);
        jbtn_savingsAcc.addActionListener(this);
        jbtn_currentAcc.addActionListener(this);
        jbtn_changePin.addActionListener(this);
        jbtn_back.addActionListener(this);
        jbtn_createCurrentAcc.addActionListener(this);
        jbtn_SavingAccCreate.addActionListener(this);
        jbtn_tranfer.addActionListener(this);
        jbtn_deposit.addActionListener(this);
        jbtn_withdraw.addActionListener(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPane = new javax.swing.JLayeredPane();
        jPanel_loginScreen = new javax.swing.JPanel();
        jbtn_login = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jlbl_title = new javax.swing.JLabel();
        jtxt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel_createSavingsAcc = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jbtn_SavingAccCreate = new javax.swing.JButton();
        jPanel_adminControlPanel = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jbtn_currentAcc = new javax.swing.JButton();
        jbtn_savingsAcc = new javax.swing.JButton();
        jbtn_changePin = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_createNewCurrentAcc = new javax.swing.JPanel();
        jlbl_currentacctitle = new javax.swing.JLabel();
        jlbl_accno = new javax.swing.JLabel();
        jlnl_holdername = new javax.swing.JLabel();
        jlnl_joindate = new javax.swing.JLabel();
        jlbl_balance = new javax.swing.JLabel();
        jlbl_username = new javax.swing.JLabel();
        jlbl_password = new javax.swing.JLabel();
        jtxt_accno = new javax.swing.JTextField();
        jtxt_holderName = new javax.swing.JTextField();
        jtxt_joinDate = new javax.swing.JTextField();
        jtxt_balance = new javax.swing.JTextField();
        jtxt_userName = new javax.swing.JTextField();
        jpw_createCurrentAccPw = new javax.swing.JPasswordField();
        jbtn_createCurrentAcc = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxt_createCurrentAccPIN = new javax.swing.JTextField();
        jPanel_userInterfaceCurrentAcc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_userInterfaceAccNo = new javax.swing.JLabel();
        jlbl_userInterfaceHolderName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtn_tranfer = new javax.swing.JButton();
        jbtn_deposit = new javax.swing.JButton();
        jbtn_withdraw = new javax.swing.JButton();
        jPanel_userInterfaceSavingAcc = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jLPane.setPreferredSize(new java.awt.Dimension(520, 500));

        jPanel_loginScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_loginScreen.setPreferredSize(new java.awt.Dimension(500, 500));

        jbtn_login.setText("Login");
        jbtn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_loginActionPerformed(evt);
            }
        });

        jpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpassword.setText("password");
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        jlbl_title.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jlbl_title.setText("Login screen");

        jtxt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_username.setText("Type in your username...");
        jtxt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usernameActionPerformed(evt);
            }
        });

        jLabel8.setText("usericon");

        javax.swing.GroupLayout jPanel_loginScreenLayout = new javax.swing.GroupLayout(jPanel_loginScreen);
        jPanel_loginScreen.setLayout(jPanel_loginScreenLayout);
        jPanel_loginScreenLayout.setHorizontalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel8))
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jlbl_title)))
                .addGap(0, 141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel_loginScreenLayout.setVerticalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jtxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jbtn_login)
                .addGap(66, 66, 66))
        );

        jLabel12.setText("jLabel12");

        jLabel13.setText("Account number");

        jLabel14.setText("Account holder");

        jLabel15.setText("Join date");

        jLabel16.setText("Balance");

        jLabel17.setText("username");

        jLabel18.setText("password");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jPasswordField1.setText("jPasswordField1");

        jbtn_SavingAccCreate.setText("Create!");

        javax.swing.GroupLayout jPanel_createSavingsAccLayout = new javax.swing.GroupLayout(jPanel_createSavingsAcc);
        jPanel_createSavingsAcc.setLayout(jPanel_createSavingsAccLayout);
        jPanel_createSavingsAccLayout.setHorizontalGroup(
            jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_createSavingsAccLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(76, 76, 76)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_createSavingsAccLayout.createSequentialGroup()
                        .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_createSavingsAccLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jbtn_SavingAccCreate)
                        .addGap(48, 48, 48))))
        );
        jPanel_createSavingsAccLayout.setVerticalGroup(
            jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_createSavingsAccLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel12)
                .addGap(49, 49, 49)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_SavingAccCreate))
                .addGap(30, 30, 30)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_createSavingsAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel_adminControlPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_adminControlPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jlblTitle.setText("Admin control panel");

        jbtn_currentAcc.setText("Current Account");

        jbtn_savingsAcc.setText("Savings Account");

        jbtn_changePin.setText("Change pin on existing account");

        jbtn_back.setText("Go Back");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel9.setText("Create");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel11.setText("Change");

        javax.swing.GroupLayout jPanel_adminControlPanelLayout = new javax.swing.GroupLayout(jPanel_adminControlPanel);
        jPanel_adminControlPanel.setLayout(jPanel_adminControlPanelLayout);
        jPanel_adminControlPanelLayout.setHorizontalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel9)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminControlPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn_savingsAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_currentAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_changePin, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel_adminControlPanelLayout.setVerticalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addGap(49, 49, 49)
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_currentAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_changePin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtn_savingsAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jlbl_currentacctitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbl_currentacctitle.setText("Create new current account");

        jlbl_accno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl_accno.setText("Account number");

        jlnl_holdername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlnl_holdername.setText("Holder name");

        jlnl_joindate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlnl_joindate.setText("Join date");

        jlbl_balance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl_balance.setText("Balance");

        jlbl_username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl_username.setText("User name");

        jlbl_password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl_password.setText("Password");

        jtxt_accno.setText("Enter Account Number");

        jtxt_holderName.setText("Enter Holder Name");

        jtxt_joinDate.setText("Enter Join Date");

        jtxt_balance.setText("Enter Balance");

        jtxt_userName.setText("Enter Username");

        jpw_createCurrentAccPw.setText("password");

        jbtn_createCurrentAcc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_createCurrentAcc.setText("Create!");

        jLabel10.setText("Pin");

        jtxt_createCurrentAccPIN.setText("Enter PIN number");

        javax.swing.GroupLayout jPanel_createNewCurrentAccLayout = new javax.swing.GroupLayout(jPanel_createNewCurrentAcc);
        jPanel_createNewCurrentAcc.setLayout(jPanel_createNewCurrentAccLayout);
        jPanel_createNewCurrentAccLayout.setHorizontalGroup(
            jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_createNewCurrentAccLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_currentacctitle)
                .addGap(87, 87, 87))
            .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jlnl_holdername)
                    .addComponent(jlbl_accno)
                    .addComponent(jlnl_joindate)
                    .addComponent(jlbl_balance)
                    .addComponent(jlbl_username)
                    .addComponent(jlbl_password))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                        .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxt_userName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_balance, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_joinDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_holderName)
                            .addComponent(jtxt_accno)
                            .addComponent(jpw_createCurrentAccPw))
                        .addGap(86, 86, 86)
                        .addComponent(jbtn_createCurrentAcc))
                    .addComponent(jtxt_createCurrentAccPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_createNewCurrentAccLayout.setVerticalGroup(
            jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jlbl_currentacctitle)
                .addGap(64, 64, 64)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_accno)
                    .addComponent(jtxt_accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnl_holdername)
                    .addComponent(jtxt_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_createCurrentAcc))
                .addGap(17, 17, 17)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnl_joindate)
                    .addComponent(jtxt_joinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_balance)
                    .addComponent(jtxt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_username)
                    .addComponent(jtxt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_password)
                    .addComponent(jpw_createCurrentAccPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxt_createCurrentAccPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jLabel1.setText("Current account");

        jlbl_userInterfaceAccNo.setText("Account number");

        jlbl_userInterfaceHolderName.setText("Holder name");

        jLabel4.setText("Balance");

        jLabel5.setText("Join date");

        jLabel6.setText("jLabel6");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel7.setText("jLabel7");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtn_tranfer.setText("Transfer");
        jbtn_tranfer.setToolTipText("");

        jbtn_deposit.setText("Deposit");

        jbtn_withdraw.setText("Withdraw");

        javax.swing.GroupLayout jPanel_userInterfaceCurrentAccLayout = new javax.swing.GroupLayout(jPanel_userInterfaceCurrentAcc);
        jPanel_userInterfaceCurrentAcc.setLayout(jPanel_userInterfaceCurrentAccLayout);
        jPanel_userInterfaceCurrentAccLayout.setHorizontalGroup(
            jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addComponent(jlbl_userInterfaceHolderName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addComponent(jlbl_userInterfaceAccNo)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_withdraw)
                    .addComponent(jbtn_tranfer)
                    .addComponent(jbtn_deposit))
                .addGap(96, 96, 96))
        );
        jPanel_userInterfaceCurrentAccLayout.setVerticalGroup(
            jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createSequentialGroup()
                        .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_userInterfaceAccNo)
                            .addComponent(jLabel6)
                            .addComponent(jbtn_tranfer))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_userInterfaceHolderName)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_deposit))
                    .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30)
                .addGroup(jPanel_userInterfaceCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(jbtn_withdraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );

        jLabel19.setText("Savings Account");

        jLabel20.setText("Account number");

        jLabel21.setText("Account holder");

        jLabel22.setText("Join date");

        jLabel23.setText("Balance");

        jLabel24.setText("username");

        jLabel25.setText("Password");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        jLabel28.setText("jLabel28");

        jLabel29.setText("jLabel29");

        jLabel30.setText("jLabel30");

        jPasswordField2.setText("jPasswordField2");

        jButton6.setText("Go back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_userInterfaceSavingAccLayout = new javax.swing.GroupLayout(jPanel_userInterfaceSavingAcc);
        jPanel_userInterfaceSavingAcc.setLayout(jPanel_userInterfaceSavingAccLayout);
        jPanel_userInterfaceSavingAccLayout.setHorizontalGroup(
            jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel19))
                    .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(80, 80, 80))
        );
        jPanel_userInterfaceSavingAccLayout.setVerticalGroup(
            jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel19)
                .addGap(37, 37, 37)
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26))
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel_userInterfaceSavingAccLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton6)))
                .addGap(38, 38, 38)
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28))
                .addGap(50, 50, 50)
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel29))
                .addGap(42, 42, 42)
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel30))
                .addGap(33, 33, 33)
                .addGroup(jPanel_userInterfaceSavingAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLPane.setLayer(jPanel_loginScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_createSavingsAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_adminControlPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_createNewCurrentAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_userInterfaceCurrentAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_userInterfaceSavingAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPaneLayout = new javax.swing.GroupLayout(jLPane);
        jLPane.setLayout(jLPaneLayout);
        jLPaneLayout.setHorizontalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_createNewCurrentAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_userInterfaceCurrentAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_createSavingsAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_userInterfaceSavingAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLPaneLayout.setVerticalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_createNewCurrentAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_userInterfaceCurrentAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_createSavingsAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_userInterfaceSavingAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel_userInterfaceCurrentAcc.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel_userInterfaceCurrentAcc.setVisible(false);
        jPanel_loginScreen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usernameActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void jbtn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_loginActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel_userInterfaceSavingAcc.setVisible(false);
        jPanel_loginScreen.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    private String userNamePasswordIsCorrect (String inputUsername, char[] inputPassword) {
        //boolean userNamePasswordIsCorrect =false;
        
        String url = "accountData.data";
        File file = new File(url);
        //ArrayList<Accounts> accounts = new ArrayList<Accounts>();
        if (file.exists()) {
                    try {

                        FileInputStream fi = new FileInputStream(file);
                        ObjectInputStream oi = new ObjectInputStream(fi);

                        accounts  = (ArrayList<Accounts>) oi.readObject();
                        //System.out.println("All accounts are loaded from file and stored in accounts?");
                        for (int i=0;i<accounts.size();i++) {
                            if (accounts.get(i).getUserName().matches(inputUsername)) {
                                System.out.println("userName and password check method-user name found, checking password...");
                                //System.out.println("correct password is: " + accounts.get(i).getUserPass()+" ; password entered is: "+inputPassword);
                                //if (accounts.get(i).getUserPass()==inputPassword) {
                                if(Arrays.equals(accounts.get(i).getUserPass(), inputPassword)){
                                    System.out.println("userName and password check method - user name and password found correct!");
                                    return accounts.get(i).getAccNo();}
                            
                            }
                            
                        }
                           
                        oi.close();
                        fi.close();
                        

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing stream");
                    } catch (ClassNotFoundException e2) {
                        System.out.println("Class not found");
                    }

                
                }
        System.out.println("userNamePassword check method - incorrect credentials");
        return null;
    }
    @Override
    public void actionPerformed (ActionEvent e){
        String url = "accountData.data";
        File file = new File(url);
        System.out.println("action received...");
        String AccNo=null;
        
        if (e.getSource()==jbtn_login) { 
            
                if (adminUsernameIsCorrect(jtxt_username.getText())&&adminPasswordIsCorrect(jpassword.getPassword())) {
                    System.out.println("admin account recognized... starting admin control panel");
                    jPanel_loginScreen.setVisible(false);
                    jPanel_adminControlPanel.setVisible(true);
                }
                else if (!file.exists()) {
                    System.out.println("No accounts in the bank!");
                }
                else if((AccNo=userNamePasswordIsCorrect(jtxt_username.getText(),jpassword.getPassword()))!=null) {///UNFINISHED!!!!! 
                    System.out.println("Reload file into accounts.... accno is:"+AccNo);
                    
                    jPanel_loginScreen.setVisible(false);
                    for (int i=0;i<accounts.size();i++) {
                        if (accounts.get(i).getAccNo().equals(AccNo)){
                            if (accounts.get(i) instanceof CurrentAccount) {
                                jPanel_userInterfaceCurrentAcc.setVisible(true);
                                jLabel26.setText(accounts.get(i).getAccNo());
                                //finish this
                                
                                
                            }
                            
                            else {
                                jPanel_userInterfaceSavingAcc.setVisible(true);
                                //finish this also
                            }
                        }
                    
                    }
                    //jPanel_userInterfaceCurrentAcc.setVisible(true);
                    /*if(file.exists()){ // this block shouldn't be here....
                        try {
                            FileInputStream fi = new FileInputStream(file);
                            ObjectInputStream oi = new ObjectInputStream(fi);

                            accounts  = (ArrayList<Accounts>) oi.readObject();
                            System.out.println("accounts reloaded from file... ");
                            oi.close();
                            fi.close();

                        } catch (FileNotFoundException evt) {
                            System.out.println("File not found");
                        } catch (IOException evt) {                
                            System.out.println("Error initializing stream");
                        } catch (ClassNotFoundException evt) {
                            System.out.println("Class not found");
                        }
                        
                    }
                    else System.err.println("File doesn's exist!!");*/
                    System.out.println("accounts.size: "+accounts.size());
                    for (int i=0;i<accounts.size();i++){
                        if (accounts.get(i).getAccNo().matches(AccNo)) {
                            System.out.println("account has been found... displaying data");
                            jLabel6.setText(accounts.get(i).getAccNo());
                            jLabel2.setText(accounts.get(i).getAccHolder());
                            jLabel3.setText(Double.toString(accounts.get(i).getBalance()));
                            jLabel7.setText(accounts.get(i).getJoinDate());
                            
                        
                        }
                    
                    }
                }
        }
        if (e.getSource()==jbtn_currentAcc)  {
                System.out.println("current account button pressed...");
                jPanel_adminControlPanel.setVisible(false);
                jPanel_createNewCurrentAcc.setVisible(true);
                
                
        }
        else if (e.getSource()==jbtn_createCurrentAcc) {
            
            
            CurrentAccount account = new CurrentAccount(jtxt_accno.getText(),jtxt_holderName.getText(),jtxt_joinDate.getText(),Double.parseDouble(jtxt_balance.getText()),jtxt_userName.getText(),jpw_createCurrentAccPw.getPassword(),jtxt_createCurrentAccPIN.getText());
            accounts.add(account);
                if (!file.exists()) {
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    } //catch (ClassNotFoundException e2) {
                        //System.out.println("Class not found");
                    //}

                
                }
                else {
                    System.out.println("file exist, flush, write new. !");
                    file.delete();
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    }
                    
                }
                jPanel_createNewCurrentAcc.setVisible(false);
                jPanel_adminControlPanel.setVisible(true);
        
        
        }
        else if (e.getSource()==jbtn_savingsAcc) {
            System.out.println("savings account button pressed...");
            jPanel_adminControlPanel.setVisible(false);
            jPanel_createSavingsAcc.setVisible(true);
            
        }
        else if (e.getSource()==jbtn_SavingAccCreate) {
            System.out.println("Create button was pressed!");
            SavingsAccount account = new SavingsAccount (jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),Double.parseDouble(jTextField4.getText()),jTextField5.getText(),jPasswordField1.getPassword());
            accounts.add(account);
            if (!file.exists()) {
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    } //catch (ClassNotFoundException e2) {
                        //System.out.println("Class not found");
                    //}

                
                }
                else {
                    System.out.println("file exist, flush, write new. !");
                    file.delete();
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    }
                    
                }
            jPanel_createSavingsAcc.setVisible(false);
            jPanel_adminControlPanel.setVisible(true);
            
            
        }
        
        
        else if (e.getSource()==jbtn_back) {
            System.out.println("go back button pressed...");
            jPanel_adminControlPanel.setVisible(false);
            jPanel_loginScreen.setVisible(true);
            
        }
        else if (e.getSource()==jbtn_tranfer) {
            String transferAmount=JOptionPane.showInputDialog("Enter amount to transfer");
            String transferAccNo=JOptionPane.showInputDialog("Enter account to transfer money to");
            
            
            for (int i=0;i<accounts.size();i++){
                if (accounts.get(i).getAccNo().equals(jLabel6.getText())) {
                    accounts.get(i).changeBalanceOnTransfer(-Double.parseDouble(transferAmount));
                    jLabel3.setText(Double.toString(accounts.get(i).getBalance()));
                }
                if (accounts.get(i).getAccNo().equals(transferAccNo)) {
                    accounts.get(i).changeBalanceOnTransfer(Double.parseDouble(transferAmount));
                
                }
            }
            
            if (!file.exists()) {
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    } //catch (ClassNotFoundException e2) {
                        //System.out.println("Class not found");
                    //}

                
                }
                else {
                    System.out.println("file exist, flush, write new. !");
                    file.delete();
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    }
                    
                }
            
        }
        else if (e.getSource()==jbtn_deposit) {
            String amountToDeposit = JOptionPane.showInputDialog("Enter amount to deposit");
            for (int i=0;i<accounts.size();i++) {
                if (accounts.get(i).getAccNo()==jLabel6.getText()) {
                    accounts.get(i).changeBalanceOnTransfer(Double.parseDouble(amountToDeposit));
                    jLabel3.setText(Double.toString(accounts.get(i).getBalance()));
                }
                
            }
            writeToFile();
        }
        else if (e.getSource()==jbtn_withdraw) {
            String amountToWithdraw = JOptionPane.showInputDialog("Enter amount to withdraw");
            for (int i=0;i<accounts.size();i++) {
                if (accounts.get(i).getAccNo()==jLabel6.getText()) {
                    accounts.get(i).changeBalanceOnTransfer(-Double.parseDouble(amountToWithdraw));
                    jLabel3.setText(Double.toString(accounts.get(i).getBalance()));
                }
                
            }
            writeToFile();
        }
        else if (e.getSource()==jbtn_changePin) {
            String changePIN = JOptionPane.showInputDialog("Enter account number"); 
            System.out.println("number receivd");
            readFromFile();
            for (int i=0;i<accounts.size();i++) {                
                if (accounts.get(i).getAccNo().equals(changePIN)) {
                    System.out.println("accoutn with pin has been found");
                    if (accounts.get(i) instanceof CurrentAccount) {
                        System.out.println("accoutn id as current");
                        CurrentAccount obj;
                        obj= (CurrentAccount)accounts.get(i);
                        System.out.println(obj.getUserPin());
                        String oldPIN = JOptionPane.showInputDialog("Enter old PIN"); 
                        if (obj.getUserPin().equals(oldPIN)) {
                            String newPIN = JOptionPane.showInputDialog("Enter new PIN");
                            obj.setUserPin(newPIN);
                            accounts.remove(accounts.get(i));
                            accounts.add(obj);
                            writeToFile();
                            break;
                        }
                        else JOptionPane.showMessageDialog(rootPane, "Account with that pin doesn't exist!!");
                    }
                
                }
                else System.out.println("No Account found");
            
            }
            
            System.out.println();
            for (int i=0;i<accounts.size();i++) {
                if (accounts.get(i) instanceof CurrentAccount) {
                    System.out.println("msg");
                    CurrentAccount obj2;
                    obj2 = (CurrentAccount) accounts.get(i);
                    System.out.println("Account number = "+obj2.getAccNo()+" Account pin = " + obj2.getUserPin());
                    
                    
                }}
        }
        
        else System.err.println("Unhandled event....");
        
    }
    
    private void readFromFile() {
        String url = "accountData.data";
        File file = new File(url);
        if (file.exists()) {
                    try {

                        FileInputStream fi = new FileInputStream(file);
                        ObjectInputStream oi = new ObjectInputStream(fi);

                        accounts  = (ArrayList<Accounts>) oi.readObject();
                        oi.close();
                        fi.close();
                        

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing stream");
                    } catch (ClassNotFoundException e2) {
                        System.out.println("Class not found");
                    }
    }}
    
    private void writeToFile() {
        String url = "accountData.data";
        File file = new File(url);
        if (!file.exists()) {
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    } //catch (ClassNotFoundException e2) {
                        //System.out.println("Class not found");
                    //}

                
                }
                else {
                    System.out.println("file exist, flush, write new. !");
                    file.delete();
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    }
                    
                }
    }
    
    private boolean adminUsernameIsCorrect (String inputUsername) {
        boolean isCorrect = true;
        String adminUsername = "admin";
        if (!inputUsername.matches(adminUsername)) isCorrect = false;
        return isCorrect;
    }
    private boolean adminPasswordIsCorrect (char[] inputPassword) {
        
        //function referenced from oracle docs: https://docs.oracle.com/javase/tutorial/uiswing/components/passwordfield.html
        boolean isCorrect = true;
        char[] adminPassword = { 'a', 'd', 'm', 'i', 'n'};
        if (inputPassword.length != adminPassword.length) {
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals (inputPassword, adminPassword);
        }
        //Zero out the password, for security
        Arrays.fill(adminPassword,'0');
        return isCorrect;
    }
    /**
     * Clears textfields for better functionality
     * @reference
     * https://stackoverflow.com/questions/5382436/text-box-cleared-when-receives-focus
     */
     public void clearTextFields(){
        jtxt_username.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_username.getText().equals("")){
                    jtxt_username.setText("Type in your username...");
                }else{
                    
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_username.getText().contains("Type in your username...")){
                    jtxt_username.setText("");
                }
            }
        });
        jpassword.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jpassword.getText().equals("")){
                    jpassword.setText("password");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jpassword.getText().contains("password")){
                    jpassword.setText("");
                }
            }
        });
        // End of Login form clearTextFields()
        
        // Start of CreateNewCurrentAccount form clearTextFields()
        jtxt_accno.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_accno.getText().equals("")){
                    jtxt_accno.setText("Enter Account Number");
                }else{
                    
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_accno.getText().contains("Enter Account Number")){
                    jtxt_accno.setText("");
                }
            }
        });
        jtxt_holderName.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_holderName.getText().equals("")){
                    jtxt_holderName.setText("Enter Holder Name");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_holderName.getText().contains("Enter Holder Name")){
                    jtxt_holderName.setText("");
                }
            }
        });
        jtxt_joinDate.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_joinDate.getText().equals("")){
                    jtxt_joinDate.setText("Enter Join Date");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_joinDate.getText().contains("Enter Join Date")){
                    jtxt_joinDate.setText("");
                }
            }
        });jtxt_balance.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_balance.getText().equals("")){
                    jtxt_balance.setText("Enter Balance");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_balance.getText().contains("Enter Balance")){
                    jtxt_balance.setText("");
                }
            }
        });jtxt_userName.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jtxt_userName.getText().equals("")){
                    jtxt_userName.setText("Enter Username");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jtxt_userName.getText().contains("Enter Username")){
                    jtxt_userName.setText("");
                }
            }
        });jpw_createCurrentAccPw.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                if(jpw_createCurrentAccPw.getText().equals("")){
                    jpw_createCurrentAccPw.setText("password");
                }
            }
            @Override
            public void focusGained(FocusEvent arg0) {
                // TODO Auto-generated method stub
                if(jpw_createCurrentAccPw.getText().contains("password")){
                    jpw_createCurrentAccPw.setText("");
                }
            }
        });
        // End of CreateNewCurrentAccount form clearTextFields()
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLayeredPane jLPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_adminControlPanel;
    private javax.swing.JPanel jPanel_createNewCurrentAcc;
    private javax.swing.JPanel jPanel_createSavingsAcc;
    private javax.swing.JPanel jPanel_loginScreen;
    private javax.swing.JPanel jPanel_userInterfaceCurrentAcc;
    private javax.swing.JPanel jPanel_userInterfaceSavingAcc;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbtn_SavingAccCreate;
    private javax.swing.JButton jbtn_back;
    private javax.swing.JButton jbtn_changePin;
    private javax.swing.JButton jbtn_createCurrentAcc;
    private javax.swing.JButton jbtn_currentAcc;
    private javax.swing.JButton jbtn_deposit;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JButton jbtn_savingsAcc;
    private javax.swing.JButton jbtn_tranfer;
    private javax.swing.JButton jbtn_withdraw;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlbl_accno;
    private javax.swing.JLabel jlbl_balance;
    private javax.swing.JLabel jlbl_currentacctitle;
    private javax.swing.JLabel jlbl_password;
    private javax.swing.JLabel jlbl_title;
    private javax.swing.JLabel jlbl_userInterfaceAccNo;
    private javax.swing.JLabel jlbl_userInterfaceHolderName;
    private javax.swing.JLabel jlbl_username;
    private javax.swing.JLabel jlnl_holdername;
    private javax.swing.JLabel jlnl_joindate;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JPasswordField jpw_createCurrentAccPw;
    private javax.swing.JTextField jtxt_accno;
    private javax.swing.JTextField jtxt_balance;
    private javax.swing.JTextField jtxt_createCurrentAccPIN;
    private javax.swing.JTextField jtxt_holderName;
    private javax.swing.JTextField jtxt_joinDate;
    private javax.swing.JTextField jtxt_userName;
    private javax.swing.JTextField jtxt_username;
    // End of variables declaration//GEN-END:variables
}
