/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oopatm;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.Double.parseDouble;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tadija
 */
public class ATMLoginForm extends JFrame implements ActionListener {

    /**
     * Creates new form ATMLoginForm
     */
    private ArrayList<Accounts> accounts = new ArrayList<Accounts>();
    public ATMLoginForm() {
        initComponents();
        initEventListeners();
        jPanel_loginScreen.setVisible(true);
        jPanel_adminControlPanel.setVisible(false);
        jPanel_createNewCurrentAcc.setVisible(false);
        jPanel_userInterface.setVisible(false);
    }
    
    private void initEventListeners() {
        jbtn_login.addActionListener(this);
        jbtn_savingsAcc.addActionListener(this);
        jbtn_currentAcc.addActionListener(this);
        jbtn_changePin.addActionListener(this);
        jbtn_back.addActionListener(this);
        jbtn_createCurrentAcc.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPane = new javax.swing.JLayeredPane();
        jPanel_loginScreen = new javax.swing.JPanel();
        jbtn_login = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jlbl_title = new javax.swing.JLabel();
        jtxt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel_adminControlPanel = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jbtn_currentAcc = new javax.swing.JButton();
        jbtn_savingsAcc = new javax.swing.JButton();
        jbtn_changePin = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jPanel_createNewCurrentAcc = new javax.swing.JPanel();
        jlbl_currentacctitle = new javax.swing.JLabel();
        jlbl_accno = new javax.swing.JLabel();
        jlnl_holdername = new javax.swing.JLabel();
        jlnl_joindate = new javax.swing.JLabel();
        jlbl_balance = new javax.swing.JLabel();
        jlbl_username = new javax.swing.JLabel();
        jlbl_password = new javax.swing.JLabel();
        jtxt_accno = new javax.swing.JTextField();
        jtxt_holderName = new javax.swing.JTextField();
        jtxt_joinDate = new javax.swing.JTextField();
        jtxt_balance = new javax.swing.JTextField();
        jtxt_userName = new javax.swing.JTextField();
        jpw_createCurrentAccPw = new javax.swing.JPasswordField();
        jbtn_createCurrentAcc = new javax.swing.JButton();
        jPanel_userInterface = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbl_userInterfaceAccNo = new javax.swing.JLabel();
        jlbl_userInterfaceHolderName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jPanel_loginScreen.setPreferredSize(new java.awt.Dimension(500, 500));

        jbtn_login.setText("Login");

        jpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpassword.setText("password");

        jlbl_title.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jlbl_title.setText("Login screen");

        jtxt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_username.setText("Type in your username...");

        javax.swing.GroupLayout jPanel_loginScreenLayout = new javax.swing.GroupLayout(jPanel_loginScreen);
        jPanel_loginScreen.setLayout(jPanel_loginScreenLayout);
        jPanel_loginScreenLayout.setHorizontalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jlbl_title)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jpassword))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                        .addComponent(jbtn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))))
        );
        jPanel_loginScreenLayout.setVerticalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginScreenLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlbl_title)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jtxt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jbtn_login)
                .addGap(50, 50, 50))
        );

        jPanel_adminControlPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jlblTitle.setText("Admin control panel");

        jbtn_currentAcc.setText("Create new current account");

        jbtn_savingsAcc.setText("Create new savings account");

        jbtn_changePin.setText("Change pin on existing account");

        jbtn_back.setText("Go Back");

        javax.swing.GroupLayout jPanel_adminControlPanelLayout = new javax.swing.GroupLayout(jPanel_adminControlPanel);
        jPanel_adminControlPanel.setLayout(jPanel_adminControlPanelLayout);
        jPanel_adminControlPanelLayout.setHorizontalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_savingsAcc)
                            .addComponent(jbtn_currentAcc)
                            .addComponent(jbtn_changePin)
                            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jbtn_back))))
                    .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jlblTitle)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel_adminControlPanelLayout.setVerticalGroup(
            jPanel_adminControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_adminControlPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jlblTitle)
                .addGap(34, 34, 34)
                .addComponent(jbtn_currentAcc)
                .addGap(18, 18, 18)
                .addComponent(jbtn_savingsAcc)
                .addGap(18, 18, 18)
                .addComponent(jbtn_changePin)
                .addGap(41, 41, 41)
                .addComponent(jbtn_back)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jlbl_currentacctitle.setText("Create new current account");

        jlbl_accno.setText("Account number");

        jlnl_holdername.setText("Holder name");

        jlnl_joindate.setText("Join date");

        jlbl_balance.setText("Balance");

        jlbl_username.setText("User name");

        jlbl_password.setText("Password");

        jtxt_accno.setText("enter account number");

        jtxt_holderName.setText("enter holder name");

        jtxt_joinDate.setText("enter join date");

        jtxt_balance.setText("enter balance");

        jtxt_userName.setText("enter user name");

        jpw_createCurrentAccPw.setText("enter user password");

        jbtn_createCurrentAcc.setText("Create!");

        javax.swing.GroupLayout jPanel_createNewCurrentAccLayout = new javax.swing.GroupLayout(jPanel_createNewCurrentAcc);
        jPanel_createNewCurrentAcc.setLayout(jPanel_createNewCurrentAccLayout);
        jPanel_createNewCurrentAccLayout.setHorizontalGroup(
            jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jlbl_currentacctitle))
                    .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlnl_holdername)
                            .addComponent(jlbl_accno)
                            .addComponent(jlnl_joindate)
                            .addComponent(jlbl_balance)
                            .addComponent(jlbl_username)
                            .addComponent(jlbl_password))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_joinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpw_createCurrentAccPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                                .addComponent(jtxt_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jbtn_createCurrentAcc)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel_createNewCurrentAccLayout.setVerticalGroup(
            jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_createNewCurrentAccLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jlbl_currentacctitle)
                .addGap(62, 62, 62)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_accno)
                    .addComponent(jtxt_accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnl_holdername)
                    .addComponent(jtxt_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_createCurrentAcc))
                .addGap(17, 17, 17)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnl_joindate)
                    .addComponent(jtxt_joinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_balance)
                    .addComponent(jtxt_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_username)
                    .addComponent(jtxt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_createNewCurrentAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_password)
                    .addComponent(jpw_createCurrentAccPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jLabel1.setText("User interface ");

        jlbl_userInterfaceAccNo.setText("Account number");

        jlbl_userInterfaceHolderName.setText("Holder name");

        jLabel4.setText("Balance");

        jLabel5.setText("Join date");

        jLabel6.setText("jLabel6");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel7.setText("jLabel7");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Transfer");
        jButton2.setToolTipText("");

        jButton3.setText("Deposit");

        jButton4.setText("Withdraw");

        jButton5.setText("Change PIN");

        javax.swing.GroupLayout jPanel_userInterfaceLayout = new javax.swing.GroupLayout(jPanel_userInterface);
        jPanel_userInterface.setLayout(jPanel_userInterfaceLayout);
        jPanel_userInterfaceLayout.setHorizontalGroup(
            jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1))
                    .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceLayout.createSequentialGroup()
                        .addComponent(jlbl_userInterfaceHolderName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_userInterfaceLayout.createSequentialGroup()
                        .addComponent(jlbl_userInterfaceAccNo)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(86, 86, 86))
        );
        jPanel_userInterfaceLayout.setVerticalGroup(
            jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_userInterfaceLayout.createSequentialGroup()
                        .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_userInterfaceAccNo)
                            .addComponent(jLabel6)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_userInterfaceHolderName)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30)
                .addGroup(jPanel_userInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(4, 4, 4)
                .addComponent(jButton4)
                .addGap(45, 45, 45)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );

        jLPane.setLayer(jPanel_loginScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_adminControlPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_createNewCurrentAcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPane.setLayer(jPanel_userInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPaneLayout = new javax.swing.GroupLayout(jLPane);
        jLPane.setLayout(jLPaneLayout);
        jLPaneLayout.setHorizontalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_createNewCurrentAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_userInterface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLPaneLayout.setVerticalGroup(
            jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_adminControlPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_createNewCurrentAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_userInterface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_userInterface.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel_userInterface.setVisible(false);
        jPanel_loginScreen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private String userNamePasswordIsCorrect (String inputUsername, char[] inputPassword) {
        //boolean userNamePasswordIsCorrect =false;
        
        String url = "accountData.data";
        File file = new File(url);
        //ArrayList<Accounts> accounts = new ArrayList<Accounts>();
        if (file.exists()) {
                    try {

                        FileInputStream fi = new FileInputStream(file);
                        ObjectInputStream oi = new ObjectInputStream(fi);

                        accounts  = (ArrayList<Accounts>) oi.readObject();
                        //System.out.println("All accounts are loaded from file and stored in accounts?");
                        for (int i=0;i<accounts.size();i++) {
                            if (accounts.get(i).getUserName().matches(inputUsername)) {
                                System.out.println("userName and password check method-user name found, checking password...");
                                //System.out.println("correct password is: " + accounts.get(i).getUserPass()+" ; password entered is: "+inputPassword);
                                //if (accounts.get(i).getUserPass()==inputPassword) {
                                if(Arrays.equals(accounts.get(i).getUserPass(), inputPassword)){
                                    System.out.println("userName and password check method - user name and password found correct!");
                                    return accounts.get(i).getAccNo();}
                            
                            }
                            
                        }
                           
                        oi.close();
                        fi.close();
                        

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing stream");
                    } catch (ClassNotFoundException e2) {
                        System.out.println("Class not found");
                    }

                
                }
        System.out.println("userNamePassword check method - incorrect credentials");
        return null;
    }
    @Override
    public void actionPerformed (ActionEvent e){
        String url = "accountData.data";
        File file = new File(url);
        System.out.println("action received...");
        String AccNo=null;
        
        if (e.getSource()==jbtn_login) { 
            
                if (adminUsernameIsCorrect(jtxt_username.getText())&&adminPasswordIsCorrect(jpassword.getPassword())) {
                    System.out.println("admin account recognized... starting admin control panel");
                    jPanel_loginScreen.setVisible(false);
                    jPanel_adminControlPanel.setVisible(true);
                }
                else if (!file.exists()) {
                    System.out.println("No accounts in the bank!");
                }
                else if((AccNo=userNamePasswordIsCorrect(jtxt_username.getText(),jpassword.getPassword()))!=null) {///UNFINISHED!!!!! 
                    System.out.println("Reload file into accounts.... accno is:"+AccNo);
                    jPanel_loginScreen.setVisible(false);
                    jPanel_userInterface.setVisible(true);
                    /*if(file.exists()){ // this block shouldn't be here....
                        try {
                            FileInputStream fi = new FileInputStream(file);
                            ObjectInputStream oi = new ObjectInputStream(fi);

                            accounts  = (ArrayList<Accounts>) oi.readObject();
                            System.out.println("accounts reloaded from file... ");
                            oi.close();
                            fi.close();

                        } catch (FileNotFoundException evt) {
                            System.out.println("File not found");
                        } catch (IOException evt) {                
                            System.out.println("Error initializing stream");
                        } catch (ClassNotFoundException evt) {
                            System.out.println("Class not found");
                        }
                        
                    }
                    else System.err.println("File doesn's exist!!");*/
                    System.out.println("accounts.size: "+accounts.size());
                    for (int i=0;i<accounts.size();i++){
                        if (accounts.get(i).getAccNo().matches(AccNo)) {
                            System.out.println("account has been found... displaying data");
                            jLabel6.setText(accounts.get(i).getAccNo());
                            jLabel2.setText(accounts.get(i).getAccHolder());
                            jLabel3.setText(Double.toString(accounts.get(i).getBalance()));
                            jLabel7.setText(accounts.get(i).getJoinDate());
                            
                        
                        }
                    
                    }
                }
        }
        if (e.getSource()==jbtn_currentAcc)  {
                System.out.println("current account button pressed...");
                jPanel_adminControlPanel.setVisible(false);
                jPanel_createNewCurrentAcc.setVisible(true);
                
                
        }
        else if (e.getSource()==jbtn_createCurrentAcc) {
            
            Accounts account = new Accounts(jtxt_accno.getText(),jtxt_holderName.getText(),jtxt_joinDate.getText(),Double.parseDouble(jtxt_balance.getText()),jtxt_userName.getText(),jpw_createCurrentAccPw.getPassword());
            accounts.add(account);
                if (!file.exists()) {
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    } //catch (ClassNotFoundException e2) {
                        //System.out.println("Class not found");
                    //}

                
                }
                else {
                    System.out.println("file exist, flush, write new. !");
                    file.delete();
                    try {
                        
                        FileOutputStream writeData = new FileOutputStream(file);
                        ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

                        writeStream.writeObject(accounts);
                        writeStream.flush();
                        writeStream.close();
                        System.out.println("All accounts are loaded from file and stored in accounts?");

                    } catch (FileNotFoundException e2) {
                        System.out.println("File not found");
                    } catch (IOException e2) {                
                        System.out.println("Error initializing output stream");
                        e2.printStackTrace();
                    }
                    
                }
                jPanel_createNewCurrentAcc.setVisible(false);
                jPanel_adminControlPanel.setVisible(true);
        
        
        }
        else if (e.getSource()==jbtn_savingsAcc) {
            System.out.println("savings account button pressed...");
        }
        else if (e.getSource()==jbtn_changePin) {
            System.out.println("change pin button pressed...");
        }
        else if (e.getSource()==jbtn_back) {
            System.out.println("go back button pressed...");
            jPanel_adminControlPanel.setVisible(false);
            jPanel_loginScreen.setVisible(true);
            
        }
        else System.err.println("Unhandled event....");
        
    }
    
    private boolean adminUsernameIsCorrect (String inputUsername) {
        boolean isCorrect = true;
        String adminUsername = "admin";
        if (!inputUsername.matches(adminUsername)) isCorrect = false;
        return isCorrect;
    }
    private boolean adminPasswordIsCorrect (char[] inputPassword) {
        
        //function referenced from oracle docs: https://docs.oracle.com/javase/tutorial/uiswing/components/passwordfield.html
        boolean isCorrect = true;
        char[] adminPassword = { 'a', 'd', 'm', 'i', 'n'};
        if (inputPassword.length != adminPassword.length) {
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals (inputPassword, adminPassword);
        }
        //Zero out the password, for security
        Arrays.fill(adminPassword,'0');
        return isCorrect;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLayeredPane jLPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel_adminControlPanel;
    private javax.swing.JPanel jPanel_createNewCurrentAcc;
    private javax.swing.JPanel jPanel_loginScreen;
    private javax.swing.JPanel jPanel_userInterface;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtn_back;
    private javax.swing.JButton jbtn_changePin;
    private javax.swing.JButton jbtn_createCurrentAcc;
    private javax.swing.JButton jbtn_currentAcc;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JButton jbtn_savingsAcc;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlbl_accno;
    private javax.swing.JLabel jlbl_balance;
    private javax.swing.JLabel jlbl_currentacctitle;
    private javax.swing.JLabel jlbl_password;
    private javax.swing.JLabel jlbl_title;
    private javax.swing.JLabel jlbl_userInterfaceAccNo;
    private javax.swing.JLabel jlbl_userInterfaceHolderName;
    private javax.swing.JLabel jlbl_username;
    private javax.swing.JLabel jlnl_holdername;
    private javax.swing.JLabel jlnl_joindate;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JPasswordField jpw_createCurrentAccPw;
    private javax.swing.JTextField jtxt_accno;
    private javax.swing.JTextField jtxt_balance;
    private javax.swing.JTextField jtxt_holderName;
    private javax.swing.JTextField jtxt_joinDate;
    private javax.swing.JTextField jtxt_userName;
    private javax.swing.JTextField jtxt_username;
    // End of variables declaration//GEN-END:variables
}
